window_x: 1920
window_y: 1080
mouse_sensitivity: 0.7

near_radius: 10
far_radius: 30
active_radius: 80
day_length: 720
gravity: 0.20

surface_shader_dir: shader/surface
surface_info_path: surface_texture.yaml
object_prototype_path: prototypes.yaml
skybox_texture_path: resources/img/sky.png
skybox_cube_path: resources/obj/cube_inward.obj
skybox_shader_directory: shader/skybox
