pub mod shader;
pub mod texture;
pub mod mesh;
pub mod projection;
pub mod transformation;
pub mod version;
pub mod graphics_error;
mod utility;
mod opengl_error;

pub use self::shader::ShaderProgram;
pub use self::shader::ShaderProgramBuilder;
pub use self::texture::TextureArray;
pub use self::texture::TextureArrayBuilder;
pub use self::mesh::Mesh;
pub use self::mesh::triangle::Triangle;
pub use self::projection::{ Projection, create_orthographic_projection };
pub use self::transformation::{ create_transformation_matrix, create_translation_matrix, create_rotation_matrix, create_scale_matrix, create_direction, create_orthographic_projection_matrix };
pub use self::graphics_error::GraphicsError;
pub use self::opengl_error::{ OpenglError, check_opengl_error };
pub use self::version::get_opengl_version;
